development:
  adapter: postgresql
  encoding: unicode
  database: thin_minting
  pool: 5
  username: lairdd
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: thin_minting_test
  pool: 5
  username: lairdd
  password:
