development:
  adapter: postgresql
  encoding: unicode
  database: thin_minting
  pool: 5
  username: lairdd
  password:
  host: localhost
  post: 5432

test:
  adapter: postgresql
  encoding: unicode
  database: thin_minting_test
  pool: 5
  username: lairdd
  password:
  host: localhost
  port: 5432
